
export default {
  "Beaubourg": "beaubourg",
  "Châtelet": "chatelet-4eme",
  "Cherche Midi": "cherche-midi-6eme",
  "Cadet": "cadet-9eme",
  "Saint-Lazare": "saint-lazare-9eme",
  "Magenta": "magenta-10eme",
  "Charonne": "charonne-11eme",
  "République": "republique-11eme",
  "Bastille": "bastille-12eme",
  "Diderot": "diderot-12eme",
  "Nation": "nation-12eme",
  "Picpus": "picpus-12eme",
  "Tolbiac": "cercle-tolbiac-13eme",
  "Olympiades": "olympiades-13eme",
  "Raspail": "raspail-14eme",
  "Saint-Jacques": "saintjacques-14eme",
  "Lecourbe": "lecourbe-15eme",
  "Porte de Versailles": "pte-de-versailles-15eme",
  "Dauphine": "dauphine-16eme",
  "Batignolles": "batignolles-17eme",
  "Maillot": "maillot-17eme",
  "Montmarte": "montmartre-18eme",
  "Ornano": "ornano-18eme",
  "Championnet": "championnet-18eme",
  "Bolivar": "bolivar-19eme",
  "Porte de Bagnollet": "porte-de-bagnolet-20eme",
  "Chatillon": "chatillon"
}
